### ISSUE TITLE
Add extra data to the gelf messages

### ISSUE THREAD

**Issue by hocrattot** [hedii/laravel-gelf-logger#43] opened 2023-03-22 14:47 UTC
Hi there, 

I am currently using Laravel 10 and laravel-gelf-logger 8.0.1 and have some hard times trying to have a custom processor able to add extra information to the gelf message.

When I have this it is all good, the message is sent to my graylog server :

![image](https://user-images.githubusercontent.com/21848176/226940967-84e2a445-3009-4d16-96f6-5324dc90edd7.png)

But when I add more data in the array like below, then nothing is sent to the server : 

![image](https://user-images.githubusercontent.com/21848176/226941813-15747fef-3b09-403b-bb4c-bcb20773a122.png)

Any idea of the reason ?

Thanks

**Comment by hedii** [comment] 2023-03-22 16:37
No idea, there's no reason from the code you shared, it looks ok.

Try adding the `single` log driver to a laravel log stack just before the gelf driver, so that you may see an error logged to storage/log/laravel.log

```php
'stack' => [
        'driver' => 'stack',
        'channels' => ['single', 'gelf'],
    ],
```

You may also have an issue with your graylog server.

I am closing this issue because I cannot reproduce your problem. If you write a test showing that something does not work as intended, please reopen a new one and submit a PR.

**Closed as completed by hedii** 2023-03-22 16:37 UTC
